#!/usr/bin/env python
import sys
import json

if len(sys.argv) > 1:
    j = json.loads(sys.argv[1])
else:
    j = json.load(sys.stdin)
print('stdout log')
sys.stderr.write('stderr log\n')
json.dump({'in': j, 'out': 'hello'}, sys.stdout)
print('')
